# Generated by Django 4.2.29 on 2026-08-27 10:37

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0006_partyledgerbalance_historicalpartyledgerbalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReplicationRecord',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('target_system', models.CharField(choices=[('odoo', 'odoo'), ('sage', 'sage')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('rejected', 'rejected'), ('unconfirmed', 'unconfirmed')], default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='replication_records', to='ledger.ledgerentrymeta')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblExternalReplicationRecord',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalaccountbalancesnapshot',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalaccountbalancesnapshot',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalaccountbalancesnapshot',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalpartyledgerbalance',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalpartyledgerbalance',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='historicalpartyledgerbalance',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='partyledgerbalance',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='partyledgerbalance',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='partyledgerbalance',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.CreateModel(
            name='ManualReviewQueueItem',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('replication_record', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_item', to='ledger.externalreplicationrecord')),
                ('resolved_by_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hordak.transaction')),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblManualReviewQueueItem',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManualReviewQueueItem',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replication_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.externalreplicationrecord')),
                ('resolved_by_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hordak.transaction')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical manual review queue item',
                'verbose_name_plural': 'historical manual review queue items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExternalReplicationRecord',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('target_system', models.CharField(choices=[('odoo', 'odoo'), ('sage', 'sage')], max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('rejected', 'rejected'), ('unconfirmed', 'unconfirmed')], default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.ledgerentrymeta')),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical external replication record',
                'verbose_name_plural': 'historical external replication records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
