# Generated by Django 4.2.29 on 2026-09-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_journaltypes_historicaljournaltypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaltypes',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='journaltypes',
            table='tblJournalTypes',
        ),
    ]
